### ISSUE TITLE
need to merge from m2127299045:master to data

### ISSUE THREAD

**Issue by charlesporter** [OpenSOC/opensoc-vagrant#5]
need to merge from m2127299045:master to data branch
HBASE v 0.98.12.1 is no longer available for download, 0.98.13 is the current version
( see http://www.trieuvan.com/apache/hbase/ )

**Comment by tpiscitell** [comment]
Apologies, but the repo is in a bit of a mess since the project is so young. I created the data branch to work on the data vm (flume, snort, bro, etc..) without affecting master, but ended up finding and fixing some bugs in data but not master. I can look into shoring up some of the differences to make it less cumbersome to deal with in the interim. 

Unfortunately free cycles are hard to come by. I would appreciate some merge requests to address these issues, as it seems you have addressed them locally according to #9 Also as you can see from #4 I am looking into a better way to manage these version numbers. If you have some time to test the script @chokha put in there, it would be really helpful.

**Comment by tpiscitell** [comment]
After further consideration, I don't see a need to merge those commits into data. As data is a feature branch to work on the data VM, it will get merged back into master eventually. Additionally, I would rather see effort put into working on #4 instead of playing whack-a-mole with version changes.
